env-config-vars: &env-config-vars
  MODEL: gemini-3-flash-preview

common: &common_settings
  start: gemini/start.sh
  instruction_file_name: GEMINI.md
  gateway_sni_hosts:
    - antigravity.google
    - daily-cloudcode-pa.googleapis.com
    - cloudcode-pa.googleapis.com
    - oauth2.googleapis.com
    - www.googleapis.com

gemini-default:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars

gemini-3-pro-preview:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: gemini-3-pro-preview
